gziphandler/gziphandler.go
main.go
middlewares.go

Add gzip wrapper

---

main.go
middleware/badrequest.go
middleware/logger.go

Move from flag to cli

---

Dockerfile
README.md
examples/README.md
main.go

Update docs for cli
Change -falgs to --flags

Update docs for cli

---

README.md
backend/example/example.go
backend/memory/memory.go
backend/mongo/mongo.go
backend/sqlite/sqlite.go
main.go
middleware/gizepper.go
mohawk.spec

Fix for https://github.com/MohawkTSDB/mohawk/issues/7.
cc @yaacov

Fix wrong import path in various files

---

cmd/root.go
main.go

Added default values for keys such that the precedence order of key/values is:
- config file
- flag
- default value
Also: fixed minor whitespaces as requested in #10 .
@yaacov PTAL

Added default values for keys and did minor refactoring

---

.gitignore
alerts/alert.go
alerts/utils.go
backend/sqlite/sqlite.go
cmd/root.go

- Alerts should get an alert-definitions object from user
If user did not give alerts, run without creating an alert object.
- Alerts check should run periodically and check for change in alert status
User can define the intervals for checking alerts.
- If alert status change log a json struct to a log file, optional, if status change do a post request to a remote server with json as body

Adding support for alerts

---

alerts/alert.go

Added changes to the Alerts Model as preparation to support CLI for alerts.

Added changes to the Alerts Model as preparation to support CLI

---

alerts/alert.go
alerts/utils.go
api/server.go
storage/memory/memory.go

~***This is a work in progress!***~
Adding the alert worker to check for alerts periodically.
cc : @yaacov

Adding alerts worker to check for alerts

---

alerts/README.md
alerts/alerts.go
alerts/examples/alert-buffer.py

post alert changes to an alert buffer.
add the time/value pair that triggered the status change to the alert object.
close: #53 #47

Add alerts posting

---

alerts/alerts.go
cli/root.go
main.go
server/server.go
storage/memory/memory.go

close https://github.com/MohawkTSDB/mohawk/issues/48

use fmt instead of log

---

alerts/alerts.go
cli/root.go
server/server.go

Add alert interval var

---

README.md

Update readme to include slack channel url 

---

test/mohawk.bats

@yaacov 
partially resolving #51

Adding smoke test for post and get

---

alerts/alerts.go
cli/root.go
server/server.go

add alert buffer url cli option

---

alerts/alerts.go
server/api-handler.go
server/server.go

add alerts api query

---

server/handlers/authorization.go
server/server.go
test/mohawk.bats

remove regex compile from auth

---

alerts/alerts.go
server/api-handler.go
server/handlers/authorization.go
server/handlers/badrequest.go
server/server.go
server/utils.go

Use the verbose flag for logging

---

test/mohawk.bats

Adding smoke tests for alerts on

---

alerts/README.md
alerts/examples/example.config.yaml
cli/root.go

also fix the cli of alerts method and insecure

adjust docs to new alerts

---

alerts/README.md
alerts/alert_test.go
alerts/alerts.go

@yaacov 😭 
"Come over this afternoon; I’ll be ready then".
"She can run faster than I can".

'then' is for time, 'than' is for comparison

---

cli/root.go
server/server.go
test/mohawk.bats

add basic auth

---

src/server/examples/push_metrics_example.sh

Add an example in server/examples

---

src/server/examples/push_metrics_example.sh

Pushing data in milliseconds and not in seconds @ server/examples/push_metrics_example.sh

---

mohawk.spec
src/cli/README.md
src/server/server.go
test/mohawk.bats

bugfix change
- fix duplicate bucket for stats requests

bump bugfix version
